


disabled_rules:
  - vertical_whitespace
  - colon
  - line_length
  - trailing_whitespace
  - trailing_newline
  - identifier_name
  - unused_optional_binding
  - unused_closure_parameter
  - trailing_comma
  - force_cast
  - unneeded_override


excluded:
  - Pods
  - PortfolioApp.xcworkspace
  - PortfolioAppTests
  - PortfolioAppUITests

reporter: json